#+TITLE: Textractor-Webhook
This is a [[https://github.com/Artikash/Textractor][Textractor]] extension which simply pushes your text to a webhook (for instance, to a Discord channel).

(WIP but soon) An external server is provided too, which pipes the input to a webpage directly, easier if you want to look stuff up using a pop-up dictionary.

** How To Use
1. Get the Release here, extract in the textractor folder, merge, the dll and text have to go in the same folder as the other dlls (and have to match the architecture).
2. Edit the two "webhook​_url.txt" files, put the url of your webhook matching the way it is in the provided file.

   **IMPORTANT** The URL must **absolutely** spread on two lines, with the first one ending with the domain name (like ".com"), without the backslash, and the second line must be the rest of the url.

   Really, as long as it looks like the provided file, or like below, it should be fine.
   #+begin_example
   Slack:
   https://hooks.slack.com
   services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX

   Discord:
   https://discord.com
   /api/webhooks/blablablablabla123123123
   #+end_example

3. Add the extension as you would with any other Textractor extension.

If you don't know how to set up webhooks, refer to:
  - https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  - https://api.slack.com/messaging/webhooks
  - https://support.guilded.gg/hc/en-us/articles/360038927934-Incoming-Webhooks
  - Whatever documentation your messaging app has
You can also use our provided server.

** Rate Limiting ?
Textractor automatically pushes sentences slowly if you mash clicks or skip lines, so I never managed to even remotely rate-limit it, so it should be fine? Feel free to raise an issue if you got rate limited somehow, I'll look at it (the code already has a beginning of rate-limiting mitigation).
