* Server for Textractor-Webhook
** How To Use
1. Download the release [[https://github.com/sdbversini/textractor-webhook/releases/tag/1.0.0][here]]
2. Run it
   - You can use the argument -b (or --bind) to change the binding address, useful if you want to let other computers connect to it (this is probably what you want). To let everyone connect you can use
     #+begin_src bash
-b 0.0.0.0:8000
     #+end_src
     of course, you can bind to a specific ip (eg, 192.168.1.0:8000, etc), and you'll need to handle port forwarding and whatnot, or use a vpn like openvpn/wireguard/zerotier...
   - By default, will bind to 127.0.0.1:8000 (or the first port available after that), so only the local machine will be able to transmit the contents (not very useful unless you really don't want to use a clipboard extension)
3. Modify the webhook_url.txt file appropriately
   e.g. (change the url of course)
   #+begin_example
192.168.1.25:8000
/api/push
   #+end_example
4. Head to that url, as textractor processes more lines it'll be updated automagically!

** Compiling
#+begin_example
git clone placeholder
cd placeholder/server
cargo build --release
#+end_example
And then the file is in target/release/server, you'll need the static folder as well in the same directory as the executable.

** Optional but recommended: Using the anacreon clipboard html instead of the default

If you're used to clipboard monitoring (or are curious), you probably like [[https://anacreondjt.gitlab.io/docs/texthooker/][Anacreon's texthook page]], because put bluntly, it is miles ahead of the one I provided.

You can, thankfully, use that one instead, pretty simply:
1. Download the file, as index.html, in the static folder after extraction, overwrite the file that was here before
2. Edit the index.html file, adding the following
   #+begin_src html
<script src="static/js/js.js" defer></script>
   #+end_src
before the `</body>` tag (you can unminify the html if needed etc)
3. Done!
